# Generated by Django 5.1.15 on 2026-03-04 05:37

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('hero', 5), ('intro', 10), ('property_listing', 11), ('service_selection', 12), ('philosophy_pillars', 13), ('portfolio_showcase', 14)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': False}), 1: ('wagtail.blocks.TextBlock', (), {'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'required': False}), 3: ('wagtail.blocks.BooleanBlock', (), {'default': True, 'required': False}), 4: ('wagtail.images.blocks.ImageChooserBlock', (), {'required': False}), 5: ('wagtail.blocks.StructBlock', [[('title_line_1', 0), ('title_line_2', 0), ('subtitle', 1), ('cta_label', 0), ('cta_url', 2), ('show_cta', 3), ('show_video', 3), ('bg_image', 4), ('bg_video_url', 2), ('bg_video_poster', 4)]], {}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link'], 'required': False}), 7: ('wagtail.blocks.CharBlock', (), {'required': True}), 8: ('wagtail.blocks.StructBlock', [[('value', 7), ('label', 7)]], {}), 9: ('wagtail.blocks.ListBlock', (8,), {'required': False}), 10: ('wagtail.blocks.StructBlock', [[('label', 0), ('headline', 6), ('body', 6), ('image', 4), ('cta_primary_label', 0), ('cta_primary_url', 2), ('cta_secondary_label', 0), ('cta_secondary_url', 2), ('stats', 9)]], {}), 11: ('wagtail.blocks.StructBlock', [[('enabled', 3)]], {'label': 'Property Listing'}), 12: ('wagtail.blocks.StructBlock', [[('enabled', 3)]], {'label': 'Service Selection'}), 13: ('wagtail.blocks.StructBlock', [[('enabled', 3)]], {'label': 'Philosophy Pillars'}), 14: ('wagtail.blocks.StructBlock', [[('enabled', 3)]], {'label': 'Portfolio Showcase'})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
