# Generated by Django 5.1.15 on 2026-03-04 08:01

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('for-sale', 'For Sale'), ('sold', 'Sold'), ('for-rent', 'For Rent')], max_length=20)),
                ('status', models.CharField(choices=[('For Sale', 'For Sale'), ('For Rent', 'For Rent'), ('Sold', 'Sold'), ('Pending', 'Pending')], default='For Sale', max_length=20)),
                ('location', models.CharField(help_text='Short location shown on cards', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sold_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('price_label', models.CharField(blank=True, max_length=100)),
                ('badge', models.CharField(blank=True, max_length=100)),
                ('is_new', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('beds', models.PositiveIntegerField(default=0)),
                ('baths', models.PositiveIntegerField(default=0)),
                ('sqft', models.PositiveIntegerField(default=0)),
                ('garage', models.PositiveIntegerField(default=0)),
                ('sold_date', models.CharField(blank=True, max_length=80)),
                ('days_on_market', models.PositiveIntegerField(blank=True, null=True)),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_lease', models.CharField(blank=True, max_length=100)),
                ('property_id', models.CharField(blank=True, max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('zip_code', models.CharField(blank=True, max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('map_embed_url', models.URLField(blank=True)),
                ('video_tour_url', models.URLField(blank=True)),
                ('agent_name', models.CharField(blank=True, max_length=255)),
                ('agent_title', models.CharField(blank=True, max_length=255)),
                ('agent_phone', models.CharField(blank=True, max_length=40)),
                ('agent_email', models.EmailField(blank=True, max_length=254)),
                ('agent_rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('agent_review_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('agent_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_agent_images', to='wagtailimages.image')),
                ('card_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_card_images', to='wagtailimages.image')),
                ('video_thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_video_thumbnails', to='wagtailimages.image')),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ListingAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('smart-home', 'Smart Home'), ('kitchen', 'Kitchen'), ('ocean', 'Ocean'), ('wine', 'Wine'), ('pool', 'Pool'), ('dock', 'Dock'), ('theater', 'Theater'), ('gym', 'Gym'), ('security', 'Security'), ('garden', 'Garden'), ('spa', 'Spa'), ('garage', 'Garage')], max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingDetailRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=255)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.CharField(max_length=120)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingNearbyLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=120)),
                ('distance', models.CharField(max_length=80)),
                ('type', models.CharField(choices=[('shopping', 'Shopping'), ('airport', 'Airport'), ('dining', 'Dining'), ('golf', 'Golf'), ('beach', 'Beach'), ('school', 'School'), ('hospital', 'Hospital')], max_length=20)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='nearby_locations', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingOverviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('text', models.TextField()),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='overview_items', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ListingStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('icon', models.CharField(choices=[('bed', 'Bed'), ('bath', 'Bath'), ('area', 'Area'), ('garage', 'Garage'), ('year', 'Year'), ('lot', 'Lot')], max_length=20)),
                ('value', models.CharField(max_length=120)),
                ('label', models.CharField(max_length=120)),
                ('listing', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='listings.listing')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
